### ISSUE TITLE
disable bash

### ISSUE THREAD

**Issue by timriker** [f5devcentral/application-study-tool#124]
I get 400 errors for this path. Is there a config option to disable this call?

- /mgmt/tm/util/bash

```
general config:
  data_types:
    f5.apm:
      enabled: true
    f5.cgnat:
      enabled: false
    f5.dns:
      enabled: true
    f5.dos:
      enabled: false
    f5.firewall:
      enabled: false
    f5.gtm:
      enabled: true
    f5.policy.asm:
      enabled: false
    f5.policy.nat:
      enabled: false
    f5.policy.firewall:
      enabled: false
    f5.policy.api_protection:
      enabled: false

```

Also, what is the difference between f5.gtm and f5.dns?
