### ISSUE TITLE
/etc/prometheus/prometheus.yml: permission denied"

### ISSUE THREAD

**Issue by DahlPatric** [f5devcentral/application-study-tool#81]
**Describe the bug**
prometheus        | ts=2025-01-22T14:46:30.165Z caller=main.go:549 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: permission denied"

**Desktop (please complete the following information):**
 - RedHat 9

**Additional context**
Added file manually, still same problem when running docker compose up

Logs :
```
prometheus        | ts=2025-01-22T14:46:16.560Z caller=main.go:184 level=info msg="Experimental OTLP write receiver enabled"
prometheus        | ts=2025-01-22T14:46:16.560Z caller=main.go:549 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: permission denied"
prometheus exited with code 2
```

**Comment by mikempw** [comment]
Can you provide more details? Rodman, open shift etc..

**Comment by DahlPatric** [comment]
> Can you provide more details? Podman, open shift etc..

```
# docker --version
Docker version 27.5.0, build a187fa5
```

```
# cat /proc/version
Linux version 5.14.0-503.19.1.el9_5.x86_64 (mockbuild@x86-64-05.build.eng.rdu2.redhat.com) (gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-2), GNU ld version 2.35.2-54.el9) #1 SMP PREEMPT_DYNAMIC Fri Dec 6 15:53:53 EST 2024

```

**Comment by mikempw** [comment]
Ok, thanks. Can you run ls -lha on the folder and paste results.

**Comment by pteiber** [comment]
Is SELinux enabled on this host? What is the output from `getenforce`?

**Comment by DahlPatric** [comment]
> Ok, thanks. Can you run ls -lha on the folder and paste results.

```
# ls -lha
total 16K
drwxr-x---    2 root root   28 Jan 22 15:43 .
drwxr-xr-x. 116 root root 8.0K Jan 22 19:04 ..
```
File was not there from the beginning, I created and added the content below.

```
 global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'otel-collector'
    scrape_interval: 30s
    static_configs:
      - targets: ['otel-collector:8888']
```
