### ISSUE TITLE
Hitting Prometheus metrics limits consistently

### ISSUE THREAD

**Issue by ahernandez1801** [f5devcentral/application-study-tool#82]
**Describe the bug**
After adding too many controllers to AST, we constantly hit the Grafana Enterprise Metrics rate limits. 

**To Reproduce**
Add 100+ controllers to AST, view logs, see metrics rate limits hit

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/eb2cc5e4-7388-49fd-a293-53dcaeff851e)
![Image](https://github.com/user-attachments/assets/f373286b-245b-4e99-85c8-7110f4e19391)

**Desktop (please complete the following information):**
Running in a Kubernetes environment, reporting to Grafana Enterprise Metrics.
 - OS: 

**Additional context**
After discussing with internal GEM team, they recommend combining metrics that could be derived from existing metrics, and dropping un-necessary metrics.

**Attachments**
If the issue is in regards to missing data in dashboards, please also run the following from the installed host and attach the output:

```
curl 'localhost:9090/federate?match[]=%7B__name__%3D~"f5.%2A"%7D'
```

Logs for the collector can be gathered with:
```
docker logs application-study-tool-otel-collector-1 --tail 1000
```

**Comment by clhainf5** [comment]
Hi there, since you're sending to your own in-house prometheus endpoint, there's not a ton we can modify  in this repo to fix things. I think the options are:

1) Talk to your platform owner about increasing the rate limit on that tenant.
2) Selectively disable (or filter out via processor) some metrics with high cardinality that you don't want to prioritize.

To disable a particular metric from export, you can add the following to the receiver config (if you're using the config scripts, this can be set in either the ast_defaults.yaml or per-bigip in bigip_configs.yaml, but iirc your managing manually so it's more like this):

```
receivers:
  bigip/1:
    endpoint: "https://10.0.0.1"
    ...
    metrics:
      f5.license.expires_at:
        enabled: false
      f5.module.provision.generation:
        enabled: false
```
 
You can also turn off all collection and export for all metrics of a given data type via:
```
receivers:
  bigip/1:
    endpoint: "https://10.0.0.1"
    ...
    data_types:
      f5.ssl_certificate:
        enabled: false
```

**Comment by clhainf5** [comment]
Looking closer at the log messages, seems like the issue is mostly with that f5_pool_member_availability_ratio metric. There are 3 "states" per-pool-member, and boolean series for each (available, unknown, offline). If upping the limit isn't an option, you might consider just filtering out the unknown and offline series (leaving you with just f5_pool_member_availability_ratio{availability_state="available"} = 0 or 1... which might be preferable to deleting it outright

Something like this should be close (you'd then apply this filter as part of the pipeline for the receivers):
```
processors:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md
  filter/remove-offline-unknown:
    error_mode: ignore
    metrics:
      datapoint:
        - metric.name == "f5.pool_member.availability" and (metric.attribute["availability.state"] == "offline" or metric.attribute["availability.state"] == "unknown")
```
