### ISSUE TITLE
Add explicit listen interface to otel-collector self-telemetry

### ISSUE THREAD

**Issue by clhain** [f5devcentral/application-study-tool#90]
Changes in upstream otel collector disallow traffic from the prometheus instance with the default configs. Need to add the following to the default service section:

```yaml
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
```
